### ISSUE TITLE
[RotatingHeads2] Plugin RotatingHeads2 v1.0.3 generated an exception while executing task 106

### ISSUE THREAD

**Issue by NoltoxGit** [Gennario/RotatingHeads2#2]
Hello,
When i set the plugin for the first time in my server, this make me a lot of errors in my console.

Logs [here](https://mclo.gs/0uM9jIm).
Can you fix this bug please ?

Thank you so much !
~ Noltox ~

**Comment by Gennario** [comment]
Hello. Default heads are in non-existent worlds. This bug will be fixed, for now just edit the world for the default heads in their files.

**Comment by NoltoxGit** [comment]
Hello,
Thank you so much for help, it's work ! :)
