### ISSUE TITLE
Rare race condition

### ISSUE THREAD

**Issue by SolsticeSpectrum** [Gennario/RotatingHeads2#7]
This happens very rarely but sometimes index out of bounds is thrown
![image](https://github.com/Gennario/RotatingHeads2/assets/38611351/40d9d9d9-40cf-448e-a381-7096edf19a9d)
I am too lazy to fire up IntelliJ and properly debug this
First I thought it's caused by `layers.add(player);` because the first two entries in the stack trace point to this same line
![image](https://github.com/Gennario/RotatingHeads2/assets/38611351/34624ec0-491f-4d4f-82cb-ca284ab4874f)
![image](https://github.com/Gennario/RotatingHeads2/assets/38611351/5d51ae7c-ff59-4124-a764-12a450d2565f)
however `add` function can't possible throw such error unless you try to access the list from two or more different threads,
I am not sure if you're using multithreading but if you do, use `synchronizedList`

Anyway the third entry in the stack trace points to this line 
![image](https://github.com/Gennario/RotatingHeads2/assets/38611351/7d702530-1d61-4aa3-80e1-95840e38e529)
which is honestly probably the root of the problem and the two traces above that are not related, my guess is that `player` isn't in the `ArrayList<>(Main.getInstance().getHeads().values())`

Anyway it's either multithreading issue or you don't check if the player is in the array here https://github.com/Gennario/RotatingHeads2/blob/main/src/main/java/cz/gennario/newrotatingheads/system/HeadRunnable.java#L28C43-L28C43

**Comment by DarkReaper231** [comment]
Quick idea, some callbacks in Paper are called on different threads, check the docs to see which ones

**Comment by DarkReaper231** [comment]
Could be also caused by `runTaskTimerAsynchronously`
